name = "school-rpg-game-pages"
pages_build_output_dir = "."
compatibility_date = "2026-07-20"

[[durable_objects.bindings]]
name = "GAME_SESSION_DO"
class_name = "MyDurableObject"
script_name = "school-rpg-session-do"
